# Generated by Django 5.2.8 on 2025-11-13 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do exame')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('trl_horas', models.PositiveIntegerField(default=24, verbose_name='Tempo de resposta (h)')),
                ('metodo', models.CharField(choices=[('Enzimático', 'Enzimático'), ('Colorimétrico', 'Colorimétrico'), ('Histológico', 'Histológico'), ('Microscópico', 'Microscópico'), ('Citometria de Fluxo', 'Citometria de Fluxo'), ('Químico', 'Químico'), ('Citoológico', 'Citoológico'), ('Espectrofotométrico', 'Espectrofotométrico'), ('Cultura', 'Cultura'), ('Imunológico', 'Imunológico'), ('ELISA', 'ELISA'), ('PCR / Reação em Cadeia da Polimerase', 'PCR / Reação em Cadeia da Polimerase'), ('Outro', 'Outro')], default='Outro', max_length=40, verbose_name='Método')),
                ('setor', models.CharField(choices=[('Hematologia', 'Hematologia'), ('Serologia', 'Serologia'), ('Anatomia Páthologica', 'Anatomia Páthologica'), ('Bioquímica', 'Bioquímica'), ('Microbiologia', 'Microbiologia'), ('Imunologia', 'Imunologia'), ('Parasitologia', 'Parasitologia'), ('Banco de Sangue', 'Banco de Sangue'), ('Outro', 'Outro')], default='Outro', max_length=40, verbose_name='Setor')),
                ('activo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_custom', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Ordem de Trabalho')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome completo')),
                ('numero_id', models.CharField(max_length=50, unique=True, verbose_name='Número de B.I/Passaporte')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10, verbose_name='Gênero')),
                ('contacto', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone')),
                ('proveniencia', models.CharField(blank=True, choices=[('Ambulatório', 'Ambulatório'), ('Clínica Externa', 'Clínica Externa'), ('Medicina Ocupacional', 'Medicina Ocupacional'), ('Maternidade', 'Maternidade'), ('Ginecologia', 'Ginecologia'), ('Pediatria', 'Pediatria'), ('Banco de Socorros', 'Banco de Socorros'), ('Consulta Externa', 'Consulta Externa'), ('Urologia', 'Urologia'), ('Cirurgia', 'Cirurgia'), ('Dentária', 'Dentária'), ('Oftalmologia', 'Oftalmologia'), ('Outro', 'Outro')], default='Outro', max_length=50, verbose_name='Proveniência')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('data_registo', models.DateTimeField(auto_now_add=True, verbose_name='Data de registo')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ExameCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campo', models.CharField(max_length=80, verbose_name='indicador')),
                ('tipo', models.CharField(choices=[('NUM', 'Numérico'), ('TXT', 'Texto')], default='NUM', max_length=3, verbose_name='resultado')),
                ('potencia', models.CharField(blank=True, choices=[('x100000', 'x1000000'), ('x1000', 'x1000'), ('x1000', 'x1000'), ('x1000000', 'x1000000')], default='x1000000', max_length=8, verbose_name='potência')),
                ('unidade', models.CharField(blank=True, max_length=8, verbose_name='unidade S.I.')),
                ('valor_referencia', models.CharField(blank=True, max_length=80, verbose_name='Valor de referência')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='lab.exame')),
            ],
            options={
                'verbose_name': 'Campo de Exame',
                'verbose_name_plural': 'Campos de Exame',
                'ordering': ['exame', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='RequisicaoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_custom', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Ordem de Trabalho')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('PEND', 'Pendente'), ('VAL', 'Validada')], default='PEND', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Analista responsável')),
                ('exames', models.ManyToManyField(related_name='requisicoes', to='lab.exame')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='lab.paciente')),
            ],
            options={
                'verbose_name': 'Requisição',
                'verbose_name_plural': 'Requisições',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_custom', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Ordem de Trabalho')),
                ('resultado', models.CharField(blank=True, max_length=120, verbose_name='Resultado')),
                ('validado', models.BooleanField(default=False, verbose_name='Validado')),
                ('data_validacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de validação')),
                ('exame_campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='lab.examecampo', verbose_name='Exame')),
                ('referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_referencia', to='lab.examecampo', verbose_name='Referência')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='lab.requisicaoanalise')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_unidade', to='lab.examecampo', verbose_name='Unidade')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validacoes_resultado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['requisicao', 'exame_campo'],
            },
        ),
    ]
