# Generated by Django 5.2.7 on 2025-11-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='descricao',
        ),
        migrations.AddField(
            model_name='exame',
            name='metodo',
            field=models.CharField(choices=[('Enzimático', 'Enzimático'), ('Enzimático‑Híbrido', 'Enzimático‑Híbrido'), ('Colorimétrico', 'Colorimétrico'), ('Espectrofotométrico', 'Espectrofotométrico'), ('Cromatográfico', 'Cromatográfico'), ('Cromatográfico Acoplado', 'Cromatográfico Acoplado (ex: LC-MS/MS)'), ('Microscópico', 'Microscópico'), ('Separação Físico‑Química', 'Separação Físico‑Química'), ('Cultura', 'Cultura'), ('Coprocultura', 'Coprocultura'), ('Urocultura', 'Urocultura'), ('Cultura Oral', 'Cultura Oral'), ('Cultura Bucal', 'Cultura Bucal'), ('Cultura Vaginal', 'Cultura Vaginal'), ('Imunológico', 'Imunológico'), ('Fluorimétrico', 'Fluorimétrico'), ('Luminescente / Quimioluminescente', 'Luminescente / Quimioluminescente'), ('Citometria de Fluxo', 'Citometria de Fluxo'), ('PCR / Reação em Cadeia da Polimerase', 'PCR / Reação em Cadeia da Polimerase'), ('RT-PCR / Transcrição Reversa PCR', 'RT-PCR / Transcrição Reversa PCR'), ('ELISA', 'ELISA'), ('IHC', 'IHC'), ('IHC-Citometria', 'IHC-Citometria'), ('Outro', 'Outro')], default='Outro', max_length=40, verbose_name='Método'),
        ),
        migrations.AddField(
            model_name='exame',
            name='setor',
            field=models.CharField(choices=[('Hematologia', 'Hematologia'), ('Bioquímica', 'Bioquímica'), ('Microbiologia', 'Microbiologia'), ('Imunologia', 'Imunologia'), ('Parasitologia', 'Parasitologia'), ('Sorologia', 'Sorologia'), ('Urinário', 'Urinário'), ('Reumatologia', 'Reumatologia'), ('Endocrinologia', 'Endocrinologia'), ('Toxicologia', 'Toxicologia'), ('Genética', 'Genética'), ('Hormonal', 'Hormonal'), ('Radiologia', 'Radiologia'), ('Outro', 'Outro')], default='Outro', max_length=40, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='proveniencia',
            field=models.CharField(blank=True, choices=[('Ambulatório', 'Ambulatório'), ('Clínica Externa', 'Clínica Externa'), ('Medicina Ocupacional', 'Medicina Ocupacional'), ('Maternidade', 'Maternidade'), ('Ginecologia', 'Ginecologia'), ('Pediatria', 'Pediatria'), ('Banco de Socorros', 'Banco de Socorros'), ('Consulta Externa', 'Consulta Externa'), ('Urologia', 'Urologia'), ('Cirurgia', 'Cirurgia'), ('Dentária', 'Dentária'), ('Oftalmologia', 'Oftalmologia'), ('Outro', 'Outro')], default='Outro', max_length=50, verbose_name='Proveniência'),
        ),
    ]
