# Generated by Django 5.2.7 on 2025-11-04 21:03

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, help_text='Endereço de email do paciente', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do registo do paciente', verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='Data de nascimento do paciente', null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], help_text='Gênero do paciente', max_length=32, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historico_medico',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico Médico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nacionalidade',
            field=django_countries.fields.CountryField(blank=True, default='MZ', help_text='Nacionalidade do paciente', max_length=2, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nid',
            field=models.CharField(editable=False, help_text='Número de Identificação do Paciente', max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='NID'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(help_text='Nome completo do paciente', max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='proveniencia',
            field=models.CharField(blank=True, choices=[('Serviço de Urgência de Reanimação', 'Serviço de Urgência de Reanimação'), ('Pediatria', 'Pediatria'), ('Cirurgia', 'Cirurgia'), ('Ginecologia', 'Ginecologia'), ('Obstetricia', 'Obstetricia'), ('Urologia', 'Urologia'), ('Medicina Homem', 'Medicina Homem'), ('Medicina Mulher', 'Medicina Mulher'), ('Oftalmologia', 'Oftalmologia'), ('Consulta Externa', 'Consulta Externa'), ('Dentisteria', 'Dentisteria'), ('Laboratório', 'Laboratório'), ('Radiologia', 'Radiologia'), ('Outros', 'Outros')], default='Pediatria', help_text='Unidade de proveniência do paciente', max_length=128, verbose_name='Proveniência'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='residencia',
            field=models.CharField(blank=True, help_text='Endereço de residência do paciente', max_length=255, verbose_name='Residência'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Número de telefone do paciente', max_length=128, null=True, region='MZ', verbose_name='Telefone'),
        ),
    ]
