# Generated by Django 5.2.8 on 2025-11-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoitem',
            name='resultado',
        ),
        migrations.AddField(
            model_name='examecampo',
            name='valor_escolha',
            field=models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo'), ('Indeterminado', 'Indeterminado'), ('Invalido', 'Inválido')], max_length=20, verbose_name='Escolha'),
        ),
        migrations.AddField(
            model_name='examecampo',
            name='valor_numerico',
            field=models.FloatField(blank=True, null=True, verbose_name='Numérico'),
        ),
        migrations.AddField(
            model_name='examecampo',
            name='valor_percentagem',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentagem'),
        ),
        migrations.AddField(
            model_name='examecampo',
            name='valor_texto',
            field=models.TextField(blank=True, verbose_name='Texto'),
        ),
        migrations.AddField(
            model_name='resultadoitem',
            name='valor_escolha',
            field=models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo'), ('Indeterminado', 'Indeterminado'), ('Invalido', 'Inválido')], max_length=20, null=True, verbose_name='Escolha'),
        ),
        migrations.AddField(
            model_name='resultadoitem',
            name='valor_numerico',
            field=models.FloatField(blank=True, null=True, verbose_name='Numérico'),
        ),
        migrations.AddField(
            model_name='resultadoitem',
            name='valor_percentagem',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentagem'),
        ),
        migrations.AddField(
            model_name='resultadoitem',
            name='valor_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='metodo',
            field=models.CharField(choices=[('Enzimático', 'Enzimático'), ('Colorimétrico', 'Colorimétrico'), ('Histológico', 'Histológico'), ('Microscópico', 'Microscópico'), ('Citometria de Fluxo', 'Citometria de Fluxo'), ('Químico', 'Químico'), ('Citoológico', 'Citoológico'), ('Espectrofotométrico', 'Espectrofotométrico'), ('Cultura', 'Cultura'), ('Imunológico', 'Imunológico'), ('ELISA', 'ELISA'), ('PCR / Reação em Cadeia da Polimerase', 'PCR / Reação em Cadeia da Polimerase'), ('Outro', 'Outro')], default='Outro', max_length=40, verbose_name='Método'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='setor',
            field=models.CharField(choices=[('Hematologia', 'Hematologia'), ('Serologia', 'Serologia'), ('Anatomia Páthologica', 'Anatomia Páthologica'), ('Bioquímica', 'Bioquímica'), ('Microbiologia', 'Microbiologia'), ('Imunologia', 'Imunologia'), ('Parasitologia', 'Parasitologia'), ('Banco de Sangue', 'Banco de Sangue'), ('Outro', 'Outro')], default='Outro', max_length=40, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='examecampo',
            name='tipo',
            field=models.CharField(choices=[('NUM', 'Numérico'), ('TXT', 'Texto'), ('PRC', 'Percentagem'), ('CHC', 'Escolha')], default='TXT', max_length=3, verbose_name='Tipo de Resultado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_custom',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Ordem de Trabalho'),
        ),
        migrations.AlterField(
            model_name='requisicaoanalise',
            name='id_custom',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Ordem de Trabalho'),
        ),
        migrations.AlterField(
            model_name='requisicaoanalise',
            name='status',
            field=models.CharField(choices=[('PEND', 'Pendente'), ('VAL', 'Validada')], default='PEND', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='resultadoitem',
            name='id_custom',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Ordem de Trabalho'),
        ),
    ]
