# Generated by Django 5.2.7 on 2025-10-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='inserido_por',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='valor',
        ),
        migrations.AlterField(
            model_name='resultado',
            name='resultado',
            field=models.TextField(blank=True, null=True, verbose_name='Resultado'),
        ),
    ]
