# Generated by Django 5.2.7 on 2025-11-02 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Designação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Designação',
                'verbose_name_plural': 'Designações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Método')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Método',
                'verbose_name_plural': 'Métodos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='exame',
            options={'ordering': ['designacao__nome', 'nome'], 'verbose_name': 'Exame', 'verbose_name_plural': 'Exames'},
        ),
        migrations.AlterField(
            model_name='exame',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição do exame', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exame',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Exame'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='trl_horas',
            field=models.PositiveIntegerField(default=24, verbose_name='TRL (horas)'),
        ),
        migrations.AddField(
            model_name='exame',
            name='designacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='exames', to='lab.designacao', verbose_name='Designação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exame',
            name='metodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exames', to='lab.metodo', verbose_name='Método'),
        ),
    ]
