# Generated by Django 5.2.7 on 2025-10-23 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='resiltado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='inserido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_inseridos', to=settings.AUTH_USER_MODEL, verbose_name='O Analista Responsavel'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='valor',
            field=models.CharField(blank=True, max_length=128, verbose_name='Resultado analitico'),
        ),
    ]
