# Generated by Django 5.2.7 on 2025-11-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_remove_exame_descricao_exame_metodo_exame_setor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoitem',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='resultadoitem',
            name='valor_referencia',
        ),
    ]
