# Generated by Django 5.2.7 on 2025-11-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_designacao_metodo_alter_exame_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, verbose_name='NID'),
        ),
    ]
