# Generated by Django 5.2.7 on 2025-10-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_resultado_resiltado_alter_resultado_inserido_por_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultado',
            old_name='resiltado',
            new_name='resultado',
        ),
    ]
