# Generated by Django 5.2.8 on 2025-11-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_remove_resultadoitem_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoitem',
            name='valor_numerico',
            field=models.FloatField(blank=True, null=True, verbose_name='Resultado Numérico'),
        ),
        migrations.AlterField(
            model_name='resultadoitem',
            name='valor_percentagem',
            field=models.FloatField(blank=True, null=True, verbose_name=' Resultado em Percentagem'),
        ),
        migrations.AlterField(
            model_name='resultadoitem',
            name='valor_texto',
            field=models.CharField(blank=True, null=True, verbose_name='Resultado Observado'),
        ),
    ]
