# Generated by Django 5.2.7 on 2025-11-04 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_paciente_email_alter_paciente_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodo',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='exame',
            name='designacao',
            field=models.ForeignKey(help_text='Sector de análise ao qual o exame pertence', on_delete=django.db.models.deletion.PROTECT, related_name='exames', to='lab.designacao', verbose_name='Sector de Análise'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='metodo',
            field=models.ForeignKey(blank=True, help_text='Método utilizado para realizar o exame, exemplo: Enzimático, Colorimétrico, etc.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exames', to='lab.metodo', verbose_name='Método'),
        ),
        migrations.AlterField(
            model_name='examecamporesultado',
            name='exame',
            field=models.ForeignKey(help_text='Exame ao qual este campo pertence', on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='lab.exame', verbose_name='Exame'),
        ),
        migrations.AlterField(
            model_name='examecamporesultado',
            name='nome_campo',
            field=models.CharField(db_index=True, help_text='Nome do campo de resultado do exame', max_length=255, unique=True, verbose_name='Nome do campo'),
        ),
        migrations.AlterField(
            model_name='examecamporesultado',
            name='obrigatorio',
            field=models.BooleanField(default=True, help_text='Indica se o campo é obrigatório', verbose_name='Obrigatório'),
        ),
        migrations.AlterField(
            model_name='examecamporesultado',
            name='tipo_campo',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('bool', 'Sim/Não'), ('date', 'Data'), ('datetime', 'Data/Hora'), ('percent', 'Porcentagem')], help_text='Tipo de dado do campo de resultado', max_length=50, verbose_name='Tipo de campo'),
        ),
        migrations.AlterField(
            model_name='itemrequisicao',
            name='exame',
            field=models.ForeignKey(help_text='Exame incluído nesta requisição', on_delete=django.db.models.deletion.CASCADE, related_name='itens_requisicao', to='lab.exame', verbose_name='Exame'),
        ),
        migrations.AlterField(
            model_name='itemrequisicao',
            name='requisicao',
            field=models.ForeignKey(help_text='Requisição à qual este item pertence', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='lab.requisicaoanalise', verbose_name='Requisição'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de entrada do registo do paciente', verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historico_medico',
            field=models.TextField(blank=True, help_text='Histórico médico relevante do paciente', null=True, verbose_name='Histórico Médico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_id',
            field=models.CharField(blank=True, help_text='Número do documento de identidade do paciente: B.I., Passaporte, etc.', max_length=64, unique=True, verbose_name='Identidade'),
        ),
        migrations.AlterField(
            model_name='requisicaoanalise',
            name='analista',
            field=models.ForeignKey(blank=True, help_text='Técnico de laboratório que criou a requisição', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico de Laboratório'),
        ),
        migrations.AlterField(
            model_name='requisicaoanalise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Data e hora de criação da requisição', verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='requisicaoanalise',
            name='exames',
            field=models.ManyToManyField(blank=True, help_text='Exames incluídos nesta requisição', related_name='requisicoes', through='lab.ItemRequisicao', to='lab.exame', verbose_name='Exames requisitados'),
        ),
        migrations.AlterField(
            model_name='requisicaoanalise',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre a requisição', verbose_name='Observações adicionais'),
        ),
        migrations.AlterField(
            model_name='requisicaoanalise',
            name='paciente',
            field=models.ForeignKey(help_text='Paciente ao qual a requisição pertence', on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='lab.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='data_insercao',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora de inserção do resultado', verbose_name='Data de inserção'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='data_validacao',
            field=models.DateTimeField(blank=True, help_text='Data e hora da validação do resultado', null=True, verbose_name='Data de validação'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='exame',
            field=models.ForeignKey(help_text='Exame ao qual este resultado pertence', on_delete=django.db.models.deletion.CASCADE, to='lab.exame', verbose_name='Exame'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='requisicao',
            field=models.ForeignKey(help_text='Requisição à qual este resultado pertence', on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='lab.requisicaoanalise', verbose_name='Requisição'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='resultado',
            field=models.TextField(blank=True, help_text='Valor do resultado do exame, observações ou interpretação', null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='unidade',
            field=models.CharField(blank=True, help_text='Unidade de medida do resultado', max_length=32, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='validado',
            field=models.BooleanField(default=False, help_text='Indica se o resultado foi validado', verbose_name='Validado'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='validado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que validou o resultado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='valor_referencia',
            field=models.CharField(blank=True, help_text='Valor de referência do exame', max_length=64, verbose_name='Valor de referência'),
        ),
        migrations.AlterField(
            model_name='resultadoitem',
            name='exame_campo',
            field=models.ForeignKey(help_text='Campo de resultado do exame', on_delete=django.db.models.deletion.CASCADE, to='lab.examecamporesultado', verbose_name='Campo do exame'),
        ),
        migrations.AlterField(
            model_name='resultadoitem',
            name='requisicao',
            field=models.ForeignKey(help_text='Requisição à qual este resultado item pertence', on_delete=django.db.models.deletion.CASCADE, related_name='resultado_items', to='lab.requisicaoanalise', verbose_name='Requisição'),
        ),
        migrations.AlterField(
            model_name='resultadoitem',
            name='resultado',
            field=models.CharField(blank=True, db_index=True, help_text='Valor do resultado do campo do exame', max_length=128, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='resultadoitem',
            name='unidade',
            field=models.CharField(blank=True, help_text='Unidade de medida do resultado', max_length=32, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='resultadoitem',
            name='valor_referencia',
            field=models.CharField(blank=True, help_text='Valor de referência do campo do exame', max_length=64, verbose_name='Valor de referência'),
        ),
    ]
