# Generated by Django 5.2.7 on 2025-11-02 02:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_remove_resultado_inserido_por_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadoitem',
            old_name='valor',
            new_name='resultado',
        ),
        migrations.AddField(
            model_name='requisicaoanalise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exame',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Exames'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='trl_horas',
            field=models.PositiveIntegerField(default=24, verbose_name='TRL(horas)'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='unidade',
            field=models.CharField(blank=True, max_length=32, verbose_name='Unidades'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='valor_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=32, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historico_medico',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='NID'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=64, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='Identidade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='proveniencia',
            field=models.CharField(blank=True, max_length=128, verbose_name='Proveniência'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Telefone'),
        ),
    ]
