# Generated by Django 5.2.8 on 2025-11-13 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_requisicaoanalise_numero_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numero_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de B.I/Passaporte'),
        ),
        migrations.AlterField(
            model_name='requisicaoanalise',
            name='numero_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_id', to='lab.paciente', verbose_name='N° B.I./PASS/ID'),
        ),
    ]
