# Generated by Django 5.2.8 on 2025-11-13 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_paciente_numero_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicaoanalise',
            name='analista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico de Laboratório'),
        ),
        migrations.AlterField(
            model_name='requisicaoanalise',
            name='numero_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_id', to='lab.paciente', verbose_name='Número de B.I./PASS/ID'),
        ),
    ]
