# Generated by Django 5.2.7 on 2025-11-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_remove_resultadoitem_unidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoitem',
            name='unidade',
            field=models.CharField(blank=True, max_length=20, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='resultadoitem',
            name='valor_referencia',
            field=models.CharField(blank=True, max_length=80, verbose_name='Valor de referência'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='metodo',
            field=models.CharField(choices=[('Enzimático', 'Enzimático'), ('Enzimático-Híbrido', 'Enzimático-Híbrido'), ('Colorimétrico', 'Colorimétrico'), ('Espectrofotométrico', 'Espectrofotométrico'), ('Cromatográfico', 'Cromatográfico'), ('Cromatográfico Acoplado', 'Cromatográfico Acoplado (ex: LC-MS/MS)'), ('Microscópico', 'Microscópico'), ('Separação Físico-Química', 'Separação Físico-Química'), ('Cultura', 'Cultura'), ('Coprocultura', 'Coprocultura'), ('Urocultura', 'Urocultura'), ('Imunológico', 'Imunológico'), ('ELISA', 'ELISA'), ('PCR / Reação em Cadeia da Polimerase', 'PCR / Reação em Cadeia da Polimerase'), ('Outro', 'Outro')], default='Outro', max_length=40, verbose_name='Método'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='setor',
            field=models.CharField(choices=[('Hematologia', 'Hematologia'), ('Bioquímica', 'Bioquímica'), ('Microbiologia', 'Microbiologia'), ('Imunologia', 'Imunologia'), ('Parasitologia', 'Parasitologia'), ('Outro', 'Outro')], default='Outro', max_length=40, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de Documento'),
        ),
    ]
