# Generated by Django 5.2.8 on 2025-11-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_resultadoitem_valor_numerico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoitem',
            name='valor_escolha',
        ),
        migrations.RemoveField(
            model_name='resultadoitem',
            name='valor_numerico',
        ),
        migrations.RemoveField(
            model_name='resultadoitem',
            name='valor_percentagem',
        ),
        migrations.RemoveField(
            model_name='resultadoitem',
            name='valor_texto',
        ),
        migrations.AddField(
            model_name='resultadoitem',
            name='resultado',
            field=models.CharField(blank=True, max_length=120, verbose_name='Resultado'),
        ),
    ]
