# Generated by Django 5.2.8 on 2025-11-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_remove_resultadoitem_valor_escolha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contacto',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone'),
        ),
    ]
