# Generated by Django 5.2.8 on 2025-11-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_paciente_email_alter_paciente_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='contacto',
            field=models.IntegerField(blank=True, max_length=30, null=True, verbose_name='Telefone'),
        ),
    ]
