# Generated by Django 5.2.8 on 2025-11-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_alter_paciente_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='contacto',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone'),
        ),
    ]
